### ISSUE TITLE
In SchemaException.php line 34: [Doctrine\DBAL\Schema\SchemaException (10)] There is no table with name 'mautic_leads' in the schema

### ISSUE THREAD

**Issue by connectedbusiness-gary** [acquia/mc-cs-plugin-custom-objects#276] opened 2022-05-31 19:15 UTC
### Mautic Version

4.2.x series

### PHP version

7.4.26

### What happened?

When I tried install custom objects plugin I see this info:

`In SchemaException.php line 34:
                                                                     
  [Doctrine\DBAL\Schema\SchemaException (10)]                        
  There is no table with name 'mautic_pr.pressleads' in the schema.  
                                                                     

Exception trace:
  at /var/www/pr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:34
 Doctrine\DBAL\Schema\SchemaException::tableDoesNotExist() at /var/www/pr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:178
 Doctrine\DBAL\Schema\Schema->getTable() at /var/www/pr/app/bundles/InstallBundle/EventListener/DoctrineEventSubscriber.php:28
 Mautic\InstallBundle\EventListener\DoctrineEventSubscriber->postGenerateSchema() at /var/www/pr/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:64
 Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent() at /var/www/pr/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:409
 Doctrine\ORM\Tools\SchemaTool->getSchemaFromMetadata() at /var/www/pr/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:116
 Doctrine\ORM\Tools\SchemaTool->getCreateSchemaSql() at /var/www/pr/app/bundles/PluginBundle/Bundle/PluginBundleBase.php:47
 Mautic\PluginBundle\Bundle\PluginBundleBase::installPluginSchema() at /var/www/pr/app/bundles/PluginBundle/Bundle/PluginBundleBase.php:27
 Mautic\PluginBundle\Bundle\PluginBundleBase::onPluginInstall() at /var/www/pr/plugins/MauticRefreshSegmentButtonPluginBundle/MauticRefreshSegmentButtonPluginBundle.php:28
 MauticPlugin\MauticRefreshSegmentButtonPluginBundle\MauticRefreshSegmentButtonPluginBundle::onPluginInstall() at /var/www/pr/app/bundles/PluginBundle/Helper/ReloadHelper.php:133
 Mautic\PluginBundle\Helper\ReloadHelper->installPlugins() at /var/www/pr/app/bundles/PluginBundle/Facade/ReloadFacade.php:40
 Mautic\PluginBundle\Facade\ReloadFacade->reloadPlugins() at /var/www/pr/app/bundles/PluginBundle/Command/ReloadCommand.php:35
 Mautic\PluginBundle\Command\ReloadCommand->execute() at /var/www/pr/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/pr/vendor/symfony/console/Application.php:1027
 Symfony\Component\Console\Application->doRunCommand() at /var/www/pr/vendor/symfony/framework-bundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/pr/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /var/www/pr/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/pr/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/pr/bin/console:42

mautic:plugins:reload [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>`

### How can we reproduce this issue?

Step 1: Manually upload custom objects bundle (not through composer)
Step 2: Run mautic:plugins:reload -vvv

### Relevant log output

```shell
In SchemaException.php line 34:
                                                                     
  [Doctrine\DBAL\Schema\SchemaException (10)]                        
  There is no table with name 'mautic_pr.pressleads' in the schema.  
                                                                     

Exception trace:
  at /var/www/pr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:34
 Doctrine\DBAL\Schema\SchemaException::tableDoesNotExist() at /var/www/pr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:178
 Doctrine\DBAL\Schema\Schema->getTable() at /var/www/pr/app/bundles/InstallBundle/EventListener/DoctrineEventSubscriber.php:28
 Mautic\InstallBundle\EventListener\DoctrineEventSubscriber->postGenerateSchema() at /var/www/pr/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:64
 Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent() at /var/www/pr/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:409
 Doctrine\ORM\Tools\SchemaTool->getSchemaFromMetadata() at /var/www/pr/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:116
 Doctrine\ORM\Tools\SchemaTool->getCreateSchemaSql() at /var/www/pr/app/bundles/PluginBundle/Bundle/PluginBundleBase.php:47
 Mautic\PluginBundle\Bundle\PluginBundleBase::installPluginSchema() at /var/www/pr/app/bundles/PluginBundle/Bundle/PluginBundleBase.php:27
 Mautic\PluginBundle\Bundle\PluginBundleBase::onPluginInstall() at /var/www/pr/plugins/MauticRefreshSegmentButtonPluginBundle/MauticRefreshSegmentButtonPluginBundle.php:28
 MauticPlugin\MauticRefreshSegmentButtonPluginBundle\MauticRefreshSegmentButtonPluginBundle::onPluginInstall() at /var/www/pr/app/bundles/PluginBundle/Helper/ReloadHelper.php:133
 Mautic\PluginBundle\Helper\ReloadHelper->installPlugins() at /var/www/pr/app/bundles/PluginBundle/Facade/ReloadFacade.php:40
 Mautic\PluginBundle\Facade\ReloadFacade->reloadPlugins() at /var/www/pr/app/bundles/PluginBundle/Command/ReloadCommand.php:35
 Mautic\PluginBundle\Command\ReloadCommand->execute() at /var/www/pr/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/pr/vendor/symfony/console/Application.php:1027
 Symfony\Component\Console\Application->doRunCommand() at /var/www/pr/vendor/symfony/framework-bundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/pr/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /var/www/pr/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/pr/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/pr/bin/console:42

mautic:plugins:reload [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-06-10 15:12
This is due to a bug with the latest release of Mautic and is fixed in this PR: https://github.com/mautic/mautic/pull/11206 which will be released in the next version of Mautic, so going to close this issue as a duplicate of the existing issues reported.

**Closed as completed by RCheesley** 2022-06-10 15:12 UTC
Labels: bug
